travis:
  secure:
    BINSTAR_TOKEN: aVdYJ6t1NGXDc4uKPD1dSfIS8kVk66HMxyR8SUZBRtC7WzVGh25aoabv2Zkx6pYE2lcSCvqBXasWS8gelABXzZBwF4E0t5E+eFyGKjl1vEp/nK6vhJcsIeCLXNXAsE1IpwacJd0YClbtI3rpkm0clUyMDm0tfJLSZ6UaLJqBPR1mKDbQmfOP2SSkkZ1aovhbvQFF7zcieB1k1CzElJvzho6MD5c7Ii5KZXwNqbLRpZE8mEDI3wKHXwZ6FgbHenRuXPu/KqQBysHfq1P2JuW1jOE2UZLJpc1CoDsD90T0mdnvyhx40UeihuQokbqJKjSZdC+IAO0E33QFQk+wLg+MLGUFqijbMkTkGh7bUUDGTd8XE7KNqtUuqt+Y9AYx/rwVXpPDukHQuRXCRsAvs/XSgcIREMD9lM4GM4YbPWfml6VF37nuyZIBS4cfiNMaj1zy+2gM7nQNvXAK2gE9ZpdMyZ+ZXDk3aZ1slGozA5u5w6Are11AiqZmEAn8IbD7E+V2nCM58bKE/OJm0arvTFlj4LyIG0L1tZMeQfUITY6Vqx6NU+b9v3ogkcTexNpcmB6uSjLYvL49+F0c1K4xCXMViob9L6SukYoGsYqIZ3KxV+zJ21F59AwNRTPCPq0oiD0y+hsEssf3yuO1RgZqaPBcuWMKYsWme3Z0L1/CWywLvfE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
